import React from 'react';

const activities = [
  { icon: '☾', title: 'Ibadah Harian', text: 'Menjadi ruang yang nyaman untuk salat berjamaah dan mendekatkan diri kepada Allah.' },
  { icon: '۞', title: 'Pembinaan Umat', text: 'Wadah untuk belajar, berbagi ilmu, dan menumbuhkan kebersamaan.' },
  { icon: '♡', title: 'Kegiatan Sosial', text: 'Mendorong kepedulian, silaturahmi, dan semangat saling membantu.' },
];

export default function App() {
  return <div className="site">
    <header className="nav"><a className="brand" href="#home"><span className="brand-mark">۞</span><span><b>MASJID AS-SAFAR</b><small>BIHARUL ULUM MA'ARIF</small></span></a><nav><a href="#tentang">Tentang</a><a href="#kegiatan">Kegiatan</a><a href="#kontak">Kontak</a></nav></header>
    <main>
      <section className="hero" id="home"><div className="hero-pattern"></div><div className="hero-copy"><span className="eyebrow">RUMAH IBADAH • RUANG KEBERSAMAAN</span><h1>Melangkah dalam<br/><em>iman & kebersamaan.</em></h1><p>Selamat datang di Masjid As-Safar Biharul Ulum Ma'arif. Semoga masjid ini menjadi tempat ibadah, menuntut ilmu, dan mempererat ukhuwah.</p><a className="cta" href="#tentang">Mengenal Masjid <span>↗</span></a></div><div className="hero-art" aria-label="Ilustrasi masjid"><div className="moon"></div><div className="star s1">✦</div><div className="star s2">✧</div><div className="mosque"><div className="minaret left"><i></i></div><div className="minaret right"><i></i></div><div className="dome"><div className="crescent">☾</div></div><div className="building"><div className="arch"><div></div></div><div className="window w1"></div><div className="window w2"></div><div className="door"></div></div><div className="base"></div></div><div className="art-caption">MASJID AS-SAFAR</div></div><div className="hero-bottom"><span>مَرْحَبًا بِكُمْ</span><span>TERBUKA UNTUK UMAT</span></div></section>
      <section className="intro section" id="tentang"><div className="section-label">01 / TENTANG KAMI</div><div className="intro-content"><h2>Tempat berlabuh,<br/><em>menguatkan langkah.</em></h2><div><p>Masjid As-Safar Biharul Ulum Ma'arif hadir sebagai ruang ibadah dan kebersamaan bagi jamaah. Setelah pembangunan selesai, masjid kini telah mulai beroperasi dan menyambut jamaah dalam aktivitas sehari-hari.</p><p className="muted">Kami terus menata pelayanan dan kegiatan agar masjid dapat tumbuh bersama masyarakat.</p></div></div></section>
      <section className="activities section" id="kegiatan"><div className="section-label">02 / PERAN MASJID</div><div className="activities-head"><h2>Ruang untuk<br/><em>bertumbuh bersama.</em></h2><p>Masjid bukan hanya tempat singgah untuk beribadah, tetapi juga ruang untuk saling menguatkan.</p></div><div className="cards">{activities.map((a,i)=><article className="activity" key={a.title}><span className="activity-num">0{i+1}</span><div className="activity-icon">{a.icon}</div><h3>{a.title}</h3><p>{a.text}</p></article>)}</div></section>
      <section className="quote"><span>“</span><p>Dan sesungguhnya masjid-masjid itu adalah untuk Allah.</p><small>QS. Al-Jinn: 18 · Pengingat untuk memakmurkan rumah Allah</small></section>
      <section className="contact section" id="kontak"><div><div className="section-label">03 / SILATURAHMI</div><h2>Mari makmurkan<br/><em>rumah Allah.</em></h2><p>Jamaah dan masyarakat dipersilakan hadir serta berpartisipasi dalam kegiatan masjid.</p></div><div className="contact-card"><span className="contact-symbol">۞</span><h3>Masjid As-Safar</h3><p>Biharul Ulum Ma'arif</p><div className="contact-line"></div><small>Informasi alamat dan kontak pengurus akan ditambahkan.</small></div></section>
    </main><footer><a className="brand footer-brand" href="#home"><span className="brand-mark">۞</span><span><b>MASJID AS-SAFAR</b><small>BIHARUL ULUM MA'ARIF</small></span></a><span>© {new Date().getFullYear()} Masjid As-Safar. Semoga membawa keberkahan.</span><a href="#home">Kembali ke atas ↑</a></footer>
  </div>;
}